version: "3.8"

services:
  db:
    image: mysql
    container_name: db_cont
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=medihub
    volumes:
      - mysql_data3:/var/lib/mysql
    networks:
      - medihub_net
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  django_app:
    build:
      context: .
    image: django_app
    container_name: django_cont
    ports:
      - 8001:8001
    restart: always
    volumes:
      - static_volume:/django/staticfiles
      - media_volume:/django/media
    command: >
      sh -c "
        python3 manage.py makemigrations --noinput &&
        python3 manage.py migrate --noinput &&
        python3 manage.py collectstatic --noinput &&
        exec gunicorn main.wsgi:application --bind 0.0.0.0:8001
      "
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - medihub_net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:8001/admin || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_cont
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - medihub_net
    volumes:
      - static_volume:/django/staticfiles
      - media_volume:/django/media

volumes:
  mysql_data3:
  static_volume:
  media_volume:

networks:
  medihub_net:
