version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - django_app

  django_app:
    image: django_app
    build:
      context: .
    container_name: "django_cont"
    ports:
      - 8001:8001
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn main.wsgi --bind 0.0.0.0:8001
      "
    env_file:
      - ".env"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=medihub
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
