# Generated by Django 5.1.4 on 2025-01-23 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='Male', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('added_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(null=True)),
                ('medicine_detail', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('next_visit', models.IntegerField(default=0)),
                ('visit_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('note', models.TextField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
