# Generated by Django 5.1.4 on 2025-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='added_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
