# Generated by Django 5.1.4 on 2025-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='Male', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('mobile', models.IntegerField(null=True)),
                ('next_visit', models.IntegerField(default=0)),
                ('address', models.TextField(null=True)),
                ('detail', models.TextField(null=True)),
                ('medicine_detail', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
