# Generated by Django 5.1.4 on 2025-01-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
